// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HotRadio: typeof import('./src/components/HotRadio.vue')['default']
    HotSinger: typeof import('./src/components/HotSinger.vue')['default']
    LoginDialog: typeof import('./src/components/loginDialog/LoginDialog.vue')['default']
    MusicDetails: typeof import('./src/components/musicDetails/MusicDetails.vue')['default']
    NewDisc: typeof import('./src/components/NewDisc.vue')['default']
    NewMv: typeof import('./src/components/NewMv.vue')['default']
    Playlist: typeof import('./src/components/Playlist.vue')['default']
    PlaylistCard: typeof import('./src/components/common/PlaylistCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SongList: typeof import('./src/components/SongList.vue')['default']
    Swiper: typeof import('./src/components/common/Swiper.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
